import type { FieldPower } from '../../logic/getSolutionFromState';
import type { Direction } from '../../redux/reducers';

const Level = {
   number: 15,
   name: 'Chief’s Private Island',
   dimension: 8,
   difficulty: 'VERY-HARD',
   solution: {
    tileSolution: {
      '0': 'BURNING' as FieldPower,
      '1': null,
      '2': 'BURNING' as FieldPower,
      '3': null,
      '4': null,
      '5': null,
      '6': null,
      '7': null,
      '8': null,
      '9': null,
      '10': null,
      '11': null,
      '12': null,
      '13': null,
      '14': 'BURNING' as FieldPower,
      '15': null,
      '16': null,
      '17': null,
      '18': null,
      '19': null,
      '20': null,
      '21': null,
      '22': null,
      '23': 'BURNING' as FieldPower,
      '24': null,
      '25': null,
      '26': null,
      '27': null,
      '28': null,
      '29': null,
      '30': null,
      '31': null,
      '32': 'ELECTRIC_CURRENT' as FieldPower,
      '33': 'ELECTRIC_CURRENT' as FieldPower,
      '34': null,
      '35': null,
      '36': null,
      '37': null,
      '38': null,
      '39': null,
      '40': null,
      '41': 'ELECTRIC_CURRENT' as FieldPower,
      '42': 'ELECTRIC_CURRENT' as FieldPower,
      '43': null,
      '44': null,
      '45': null,
      '46': null,
      '47': null,
      '48': null,
      '49': null,
      '50': 'ELECTRIC_CURRENT' as FieldPower,
      '51': 'ELECTRIC_CURRENT' as FieldPower,
      '52': null,
      '53': null,
      '54': null,
      '55': 'BURNING' as FieldPower,
      '56': null,
      '57': null,
      '58': null,
      '59': null,
      '60': null,
      '61': null,
      '62': null,
      '63': null,
    },
    lightBeams: [
      {
        index: 30,
        direction: 'WEST' as Direction,
      },
      {
        index: 30,
        direction: 'WEST' as Direction,
      },
      {
        index: 30,
        direction: 'WEST' as Direction,
      },
      {
        index: 37,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 44,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 51,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 58,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 35,
        direction: 'EAST' as Direction,
      },
      {
        index: 35,
        direction: 'EAST' as Direction,
      },
      {
        index: 35,
        direction: 'EAST' as Direction,
      },
      {
        index: 44,
        direction: 'SOUTHEAST' as Direction,
      },
      {
        index: 53,
        direction: 'SOUTHEAST' as Direction,
      },
    ],
  },
 };

 export default Level;