import type { FieldPower } from '../../logic/getSolutionFromState';
import type { Direction } from '../../redux/reducers';

const Level = {
   number: 16,
   name: 'Capitol Village',
   dimension: 8,
   difficulty: 'VERY-HARD',
   solution: {
    tileSolution: {
      '0': null,
      '1': null,
      '2': null,
      '3': null,
      '4': null,
      '5': null,
      '6': null,
      '7': null,
      '8': null,
      '9': null,
      '10': null,
      '11': null,
      '12': null,
      '13': 'ELECTRIC_CURRENT' as FieldPower,
      '14': 'ELECTRIC_CURRENT' as FieldPower,
      '15': null,
      '16': null,
      '17': null,
      '18': null,
      '19': null,
      '20': null,
      '21': 'ELECTRIC_CURRENT' as FieldPower,
      '22': null,
      '23': null,
      '24': null,
      '25': null,
      '26': null,
      '27': null,
      '28': null,
      '29': null,
      '30': 'BURNING' as FieldPower,
      '31': null,
      '32': null,
      '33': null,
      '34': null,
      '35': 'BURNING' as FieldPower,
      '36': null,
      '37': 'BURNING' as FieldPower,
      '38': null,
      '39': 'BURNING' as FieldPower,
      '40': 'ELECTRIC_CURRENT' as FieldPower,
      '41': 'ELECTRIC_CURRENT' as FieldPower,
      '42': null,
      '43': 'BURNING' as FieldPower,
      '44': null,
      '45': null,
      '46': null,
      '47': null,
      '48': null,
      '49': null,
      '50': null,
      '51': null,
      '52': 'BURNING' as FieldPower,
      '53': null,
      '54': null,
      '55': null,
      '56': null,
      '57': null,
      '58': 'ELECTRIC_CURRENT' as FieldPower,
      '59': 'BURNING' as FieldPower,
      '60': null,
      '61': null,
      '62': null,
      '63': null,
    },
    lightBeams: [
      {
        index: 28,
        direction: 'WEST' as Direction,
      },
      {
        index: 28,
        direction: 'WEST' as Direction,
      },
      {
        index: 28,
        direction: 'WEST' as Direction,
      },
      {
        index: 35,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 42,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 49,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 56,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 46,
        direction: 'WEST' as Direction,
      },
      {
        index: 46,
        direction: 'WEST' as Direction,
      },
      {
        index: 37,
        direction: 'NORTHWEST' as Direction,
      },
      {
        index: 28,
        direction: 'NORTHWEST' as Direction,
      },
      {
        index: 46,
        direction: 'WEST' as Direction,
      },
      {
        index: 37,
        direction: 'NORTHWEST' as Direction,
      },
      {
        index: 28,
        direction: 'NORTHWEST' as Direction,
      },
      {
        index: 20,
        direction: 'NORTH' as Direction,
      },
      {
        index: 12,
        direction: 'NORTH' as Direction,
      },
      {
        index: 4,
        direction: 'NORTH' as Direction,
      },
      {
        index: 46,
        direction: 'WEST' as Direction,
      },
      {
        index: 37,
        direction: 'NORTHWEST' as Direction,
      },
      {
        index: 28,
        direction: 'NORTHWEST' as Direction,
      },
      {
        index: 27,
        direction: 'WEST' as Direction,
      },
      {
        index: 46,
        direction: 'WEST' as Direction,
      },
      {
        index: 53,
        direction: 'SOUTHWEST' as Direction,
      },
      {
        index: 60,
        direction: 'SOUTHWEST' as Direction,
      },
    ],
  },
 };

 export default Level;