import type { FieldPower } from '../../logic/getSolutionFromState';
import type { Direction } from '../../redux/reducers';

const Level = {
   number: 17,
   name: 'The Island Slums',
   dimension: 8,
   difficulty: 'VERY-HARD',
   solution: {
    tileSolution: {
      '0': null,
      '1': 'BURNING' as FieldPower,
      '2': null,
      '3': 'BURNING' as FieldPower,
      '4': 'BURNING' as FieldPower,
      '5': null,
      '6': 'BURNING' as FieldPower,
      '7': null,
      '8': 'BURNING' as FieldPower,
      '9': null,
      '10': null,
      '11': null,
      '12': null,
      '13': 'BURNING' as FieldPower,
      '14': null,
      '15': null,
      '16': null,
      '17': null,
      '18': null,
      '19': null,
      '20': 'ELECTRIC_CURRENT' as FieldPower,
      '21': null,
      '22': null,
      '23': null,
      '24': 'BURNING' as FieldPower,
      '25': null,
      '26': null,
      '27': null,
      '28': 'ELECTRIC_CURRENT' as FieldPower,
      '29': 'ELECTRIC_CURRENT' as FieldPower,
      '30': null,
      '31': null,
      '32': null,
      '33': null,
      '34': 'ELECTRIC_CURRENT' as FieldPower,
      '35': 'ELECTRIC_CURRENT' as FieldPower,
      '36': 'ELECTRIC_CURRENT' as FieldPower,
      '37': null,
      '38': null,
      '39': null,
      '40': null,
      '41': 'BURNING' as FieldPower,
      '42': null,
      '43': 'ELECTRIC_CURRENT' as FieldPower,
      '44': null,
      '45': null,
      '46': null,
      '47': null,
      '48': 'BURNING' as FieldPower,
      '49': null,
      '50': null,
      '51': 'ELECTRIC_CURRENT' as FieldPower,
      '52': null,
      '53': null,
      '54': null,
      '55': null,
      '56': null,
      '57': null,
      '58': null,
      '59': null,
      '60': null,
      '61': null,
      '62': null,
      '63': 'BURNING' as FieldPower,
    },
    lightBeams: [
      {
        index: 9,
        direction: 'SOUTH' as Direction,
      },
      {
        index: 20,
        direction: 'WEST' as Direction,
      },
      {
        index: 19,
        direction: 'WEST' as Direction,
      },
      {
        index: 18,
        direction: 'WEST' as Direction,
      },
      {
        index: 38,
        direction: 'SOUTH' as Direction,
      },
      {
        index: 46,
        direction: 'SOUTH' as Direction,
      },
    ],
  },
 };

 export default Level;