const ADD_TOTEM = 'ADD_TOTEM';
const CHANGE_TOTEM_SELECTION = 'CHANGE_TOTEM_SELECTION';
const CHANGE_TOTEM_DIRECTION = 'CHANGE_TOTEM_DIRECTION';
const SET_HOVERED_TOTEM_ID = 'SET_HOVERED_TOTEM_ID';

export type ACTION_TYPE = 'ADD_TOTEM' | 'CHANGE_TOTEM_SELECTION' | 'CHANGE_TOTEM_DIRECTION' | 'SET_HOVERED_TOTEM_ID'

export default { ADD_TOTEM, CHANGE_TOTEM_SELECTION, CHANGE_TOTEM_DIRECTION, SET_HOVERED_TOTEM_ID };