const ADD_TOTEM = 'ADD_TOTEM'
const CHANGE_TOTEM_SELECTION = 'CHANGE_TOTEM_SELECTION'

export type ACTION_TYPE = 'ADD_TOTEM' | 'CHANGE_TOTEM_SELECTION'

export default { ADD_TOTEM, CHANGE_TOTEM_SELECTION }