const ADD_TOTEM = 'ADD_TOTEM';
const REMOVE_TOTEM = 'REMOVE_TOTEM';
const CHANGE_TOTEM_SELECTION = 'CHANGE_TOTEM_SELECTION';
const CHANGE_TOTEM_DIRECTION = 'CHANGE_TOTEM_DIRECTION';
const SET_HOVERED_TOTEM_ID = 'SET_HOVERED_TOTEM_ID';
const SET_LEVEL = 'SET_LEVEL';

export type ACTION_TYPE = 'ADD_TOTEM' | 
'REMOVE_TOTEM' |
'CHANGE_TOTEM_SELECTION' | 
'CHANGE_TOTEM_DIRECTION' | 
'SET_HOVERED_TOTEM_ID' | 
'SET_LEVEL'

export default { 
  ADD_TOTEM, 
  REMOVE_TOTEM,
  CHANGE_TOTEM_SELECTION, 
  CHANGE_TOTEM_DIRECTION, 
  SET_HOVERED_TOTEM_ID, 
  SET_LEVEL, 
};