export const BURNING = 'BURNING'
export const FLOODED = 'FLOODED'
export const SMOKEY = 'SMOKEY'
export const STEAMY = 'STEAMY'
export const ELECTRIC_CURRENT = 'ELECTRIC_CURRENT'
export const BRIGHT = 'BRIGHT'
export const WINDY = 'WINDY'
export const EARTH = 'EARTH'